config/routes.rb
Contact::Application.routes.draw do
  devise_for :users

  resources :addresses

  root :to => "addresses#index"
  

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_attached_file :photo,
                    :url => "photos/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/images/photos/:id/:style/:basename.:extension"
  has_one :province
end

app/models/province.rb
class Province < ActiveRecord::Base
  belongs_to :address
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /addresses
  # GET /addresses.xml
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.xml
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.xml
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.xml
  def create
    # Convert B.E. back to B.C
    params[:address]["bdate"] = christian_date(params[:address]["bdate"])
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to(@address, :notice => 'Address was successfully created.') }
        format.xml  { render :xml => @address, :status => :created, :location => @address }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @address.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.xml
  def update
    @address = Address.find(params[:id])
    
    respond_to do |format|
      # Convert B.E. back to B.C
      params[:address]["bdate"] = christian_date(params[:address]["bdate"])
      if @address.update_attributes(params[:address])
        format.html { redirect_to(@address, :notice => 'Address was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @address.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.xml
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to(addresses_url) }
      format.xml  { head :ok }
    end
  end
  
  # Buddhist Era date -> be_date 13/03/2554
  def christian_date(be_date)
    if (be_date.class == Date)
      d = be_date.day
      m = be_date.month
      y = be_date.year - 543
      bc_date = "#{y}-#{m}-#{d}"
    else
      # format m/d/y
      dmy = be_date.split('/')
      d = dmy[0]
      m = dmy[1]
      y = dmy[2].to_i - 543
      bc_date = "#{y}-#{m}-#{d}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def buddhist_date(bc_date)
    if (bc_date.nil?)
      bc_date = Time.now
    end
    y = bc_date.year + 543
    m = (bc_date.month < 10) ? '0' + bc_date.month.to_s : bc_date.month
    d = (bc_date.day < 10) ? '0' + bc_date.day.to_s : bc_date.day
    be_date = "#{d}/#{m}/#{y}"
  end
end

app/views/addresses/_form.html.erb
<%= form_for(@address, :html => { :multipart => true }) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @address.photo.url !~ /missing/ %>
    <%= image_tag @address.photo.url, :border => 0 %>
    <div class="field">
      <%= f.label :photo_file_name %>:&nbsp;
      <font color="red"><i><%= @address.photo_file_name %></i></font>
    </div>
  <% end %>
  
  <div>
    <%= f.file_field :photo %>
    <hr />
  </div>
  <div class="field">
    <%= f.label 'จังหวัด' %><br />
    <%= select('address', :province_id,
        Province.all(:order => 'pname').collect {|p| [p.pname, p.pcode]}) %>
  </div>
  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label 'วันเกิด' %><br />
    <%= f.text_field :bdate, :value => buddhist_date(@address.bdate) %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<div class="welcome">
<% if user_signed_in? %>
  <%= current_user.email %> is logged in. If user is NOT you,
  click <%= link_to "Sign Out", destroy_user_session_path %>
<% else %>
  <%= link_to "Register", new_user_registration_path %> or
  <%= link_to "Sign In", new_user_session_path %>
<% end %>
</div>

<h1>Listing addresses</h1>

<table>
  <tr>
    <thead>
    <th>ชื่อ</th>
    <th>นามสกุล</th>
    <th>โทรศัพท์</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
    </thead>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.fname %></td>
    <td><%= address.lname %></td>
    <td><%= address.phone %></td>
    <td><%= address.email %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to image_tag('icons/add.png', :border => 0), new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @address.photo.url %><br />
  Photo: <font color="red"><i><%= @address.photo_file_name %></i></font>
</p>

<p>
  <b>จังหวัด:</b>
  <%= Province.find_by_pcode(@address.province_id.to_s).pname %>
</p>

<p>
  <b>Fname:</b>
  <%= @address.fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @address.lname %>
</p>

<p>
  <b>วันเกิด:</b>
  <%= buddhist_date(@address.bdate) %>
</p>

<p>
  <b>Phone:</b>
  <%= @address.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @address.email %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact</title>
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.1.custom' %>
  <%= javascript_include_tag 'jquery-1.5.1.min' %>
  <%= javascript_include_tag 'jquery-ui-1.8.1.offset.datepicker.min' %>
  <%= javascript_include_tag 'jquery-ui-calendars-th' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<p class = "alert"><%= alert %></p>
<%= yield %>

</body>
</html>